### ISSUE TITLE
Feature Request: Struct support

### ISSUE THREAD

**Issue by cholcombe973** [savant2212/xdr-rs#3]
I was just wondering if you're planning on building struct serialization into this library?  I'm working on a project that needs it.

**Comment by savant2212** [comment]
I think that more clear way - implement XdrPrimitive for your structure. Look for example https://github.com/savant2212/xdr-rs/blob/master/src/xdr.rs#L214 to String implementation.

Also, I don't know any good way to implement generic serialization of struct. IIRC there is no 'reflection' in rust and my macro-fu isn't good enough.

**Comment by cholcombe973** [comment]
Yeah I don't think Rust has reflection either :-/.

I'll try to implement XdrPrimitive.  That sounds good.  Thanks
